Update tracking.php
Elmigo/oc3_dutch_translation pull request #2
Opened 2021-12-02 21:30 UTC by SoftwareOnbekend

2021-12-03 09:00 UTC, Elmigo requested changes
Op regel 7 staat:
in de URL\'s die naar ons linkt

Is het misschien beter om "linken" te gebruiken in plaats van "linkt"?
(omdat het om URL's gaat en niet om één URL)

2021-12-04 08:06 UTC, SoftwareOnbekend reviewed
Dat is misschien wel een betere vertaling ja. :)

2021-12-04 08:18 UTC, Elmigo approved these changes

2021-12-04 08:18 UTC, Elmigo approved these changes

2021-12-04 08:19 UTC, merged